using FormFinch.JsonSchemaValidation.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;

namespace FormFinch.JsonSchemaValidation.ManualTests.Scenarios;

internal static class CompiledValidatorScenarios
{
    // Generated by: jsv-codegen generate -s Schemas/user-profile.json -o . -n FormFinch.JsonSchemaValidation.ManualTests -c CompiledValidator_UserProfile

    private const string ValidInstance = """
        {
            "username": "alice_42",
            "email": "alice@example.com",
            "age": 28,
            "bio": "Software developer",
            "tags": ["csharp", "dotnet"]
        }
        """;

    private const string InvalidInstance = """
        {
            "username": "a",
            "email": "not-an-email",
            "age": 5,
            "bio": "ok",
            "tags": ["a", "a"]
        }
        """;

    private const string SchemaJson = """
        {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "$id": "https://formfinch.com/schemas/user-profile",
            "type": "object",
            "properties": {
                "username": {
                    "type": "string",
                    "minLength": 3,
                    "maxLength": 30,
                    "pattern": "^[a-zA-Z0-9_]+$"
                },
                "email": {
                    "type": "string",
                    "format": "email"
                },
                "age": {
                    "type": "integer",
                    "minimum": 13,
                    "maximum": 150
                },
                "bio": {
                    "type": "string",
                    "maxLength": 500
                },
                "tags": {
                    "type": "array",
                    "items": { "type": "string" },
                    "maxItems": 10,
                    "uniqueItems": true
                }
            },
            "required": ["username", "email", "age"]
        }
        """;

    public static void Run(TestRunner runner)
    {
        runner.PrintSection("Compiled Validator — Pre-generated via jsv-codegen");

        var compiledValidator = new CompiledValidator_UserProfile();

        // Set up DI with compiled validator
        var services = new ServiceCollection();
        services.AddJsonSchemaValidation();
        services.AddCompiledValidators(compiledValidator);
        using var provider = services.BuildServiceProvider();
        provider.InitializeSingletonServices();

        runner.Run("Compiled — valid instance", () =>
        {
            using var doc = System.Text.Json.JsonDocument.Parse(ValidInstance);
            var isValid = compiledValidator.IsValid(doc.RootElement);
            Assert(isValid, "Expected valid");
        });

        runner.Run("Compiled — invalid instance", () =>
        {
            using var doc = System.Text.Json.JsonDocument.Parse(InvalidInstance);
            var isValid = compiledValidator.IsValid(doc.RootElement);
            Assert(!isValid, "Expected invalid");
        });

        runner.Run("Compiled vs Interpreted — results match for valid", () =>
        {
            using var doc = System.Text.Json.JsonDocument.Parse(ValidInstance);
            var compiledResult = compiledValidator.IsValid(doc.RootElement);
            var interpretedResult = JsonSchemaValidator.IsValid(SchemaJson, ValidInstance);
            Assert(compiledResult == interpretedResult,
                $"Mismatch: compiled={compiledResult}, interpreted={interpretedResult}");
        });

        runner.Run("Compiled vs Interpreted — results match for invalid", () =>
        {
            using var doc = System.Text.Json.JsonDocument.Parse(InvalidInstance);
            var compiledResult = compiledValidator.IsValid(doc.RootElement);
            var interpretedResult = JsonSchemaValidator.IsValid(SchemaJson, InvalidInstance);
            Assert(compiledResult == interpretedResult,
                $"Mismatch: compiled={compiledResult}, interpreted={interpretedResult}");
        });
    }

    private static void Assert(bool condition, string message)
    {
        if (!condition)
        {
            throw new InvalidOperationException(message);
        }
    }
}
