// Copyright (c) 2026 FormFinch VOF
// Licensed under the PolyForm Noncommercial License 1.0.0.
// See LICENSE file in the project root for full license information.

// <auto-generated>
// This code was generated by jsv-codegen.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text.Json;
using System.Text.RegularExpressions;
using FormFinch.JsonSchemaValidation.Abstractions;
using FormFinch.JsonSchemaValidation.Draft202012.Keywords.Format;

namespace FormFinch.JsonSchemaValidation.ManualTests
{
    public sealed partial class CompiledValidator_UserProfile : ICompiledValidator
    {
        [GeneratedRegex(@"^[a-zA-Z0-9_]+$", RegexOptions.None, matchTimeoutMilliseconds: 5000)]
        private static partial Regex Pattern_b935497210d3();

        public Uri SchemaUri => new Uri("https://formfinch.com/schemas/user-profile");

        public bool IsValid(JsonElement instance) => Validate_7e5769a76942(instance);

    private static bool Validate_7e5769a76942(JsonElement e)
    {
        if (e.ValueKind != JsonValueKind.Object) return false;
        if (e.ValueKind == JsonValueKind.Object)
        {
            if (!e.TryGetProperty("username", out _)) return false;
            if (!e.TryGetProperty("email", out _)) return false;
            if (!e.TryGetProperty("age", out _)) return false;
        }

        if (e.ValueKind == JsonValueKind.Object)
        {
            if (e.TryGetProperty("username", out var _prop0_))
            {
                if (!Validate_b935497210d3(_prop0_)) return false;
            }
            if (e.TryGetProperty("email", out var _prop1_))
            {
                if (!Validate_010b1dec8655(_prop1_)) return false;
            }
            if (e.TryGetProperty("age", out var _prop2_))
            {
                if (!Validate_0de32fd7a6ce(_prop2_)) return false;
            }
            if (e.TryGetProperty("bio", out var _prop3_))
            {
                if (!Validate_373775e26848(_prop3_)) return false;
            }
            if (e.TryGetProperty("tags", out var _prop4_))
            {
                if (!Validate_5571d70d2372(_prop4_)) return false;
            }
        }

        return true;
    }


    private static bool Validate_b935497210d3(JsonElement e)
    {
        if (e.ValueKind != JsonValueKind.String) return false;
        if (e.ValueKind == JsonValueKind.String)
        {
            var _str_ = e.GetString();
            if (_str_ != null && !Pattern_b935497210d3().IsMatch(_str_)) return false;
        }
        if (e.ValueKind == JsonValueKind.String)
        {
            var _str_ = e.GetString();
            if (_str_ != null)
            {
                var _len_ = new StringInfo(_str_).LengthInTextElements;
                if (_len_ < 3) return false;
                if (_len_ > 30) return false;
            }
        }

        return true;
    }


    private static bool Validate_010b1dec8655(JsonElement e)
    {
        if (e.ValueKind != JsonValueKind.String) return false;
        if (!FormatValidators.IsValidEmail(e)) return false;
        return true;
    }


    private static bool Validate_0de32fd7a6ce(JsonElement e)
    {
        if (e.ValueKind != JsonValueKind.Number) return false;
        {
            var _isInt_ = false;
            if (e.TryGetDecimal(out var _intVal_) && _intVal_ == decimal.Truncate(_intVal_)) _isInt_ = true;
            else if (System.Numerics.BigInteger.TryParse(e.ToString(), System.Globalization.CultureInfo.InvariantCulture, out _)) _isInt_ = true;
            else if (e.TryGetDouble(out var _dblVal_) && !double.IsInfinity(_dblVal_) && !double.IsNaN(_dblVal_) && Math.Abs(_dblVal_ - Math.Floor(_dblVal_)) < double.Epsilon) _isInt_ = true;
            if (!_isInt_) return false;
        }
        if (e.ValueKind == JsonValueKind.Number)
        {
            var _num_ = e.GetDouble();
            if (_num_ < 13) return false;
            if (_num_ > 150) return false;
        }

        return true;
    }


    private static bool Validate_373775e26848(JsonElement e)
    {
        if (e.ValueKind != JsonValueKind.String) return false;
        if (e.ValueKind == JsonValueKind.String)
        {
            var _str_ = e.GetString();
            if (_str_ != null)
            {
                var _len_ = new StringInfo(_str_).LengthInTextElements;
                if (_len_ > 500) return false;
            }
        }

        return true;
    }


    private static bool Validate_5571d70d2372(JsonElement e)
    {
        if (e.ValueKind != JsonValueKind.Array) return false;
        if (e.ValueKind == JsonValueKind.Array)
        {
            var _arrLen_ = e.GetArrayLength();
            if (_arrLen_ > 10) return false;
            // Check uniqueItems
            var _items_ = new List<JsonElement>(_arrLen_);
            foreach (var _item_ in e.EnumerateArray())
            {
                foreach (var _existing_ in _items_)
                {
                    if (DeepEquals(_item_, _existing_)) return false;
                }
                _items_.Add(_item_);
            }
        }

        if (e.ValueKind == JsonValueKind.Array)
        {
            var _itemIdx_ = 0;
            foreach (var _arrItem_ in e.EnumerateArray())
            {
                if (!Validate_00404e686415(_arrItem_)) return false;
                _itemIdx_++;
            }
        }

        return true;
    }


    private static bool Validate_00404e686415(JsonElement e)
    {
        if (e.ValueKind != JsonValueKind.String) return false;
        return true;
    }



        // Helper for deep equality comparison of JSON elements
        private static bool DeepEquals(JsonElement left, JsonElement right)
        {
            if (left.ValueKind != right.ValueKind) return false;
            return left.ValueKind switch
            {
                JsonValueKind.Null => true,
                JsonValueKind.True => true,
                JsonValueKind.False => true,
                JsonValueKind.String => string.Equals(left.GetString(), right.GetString(), StringComparison.Ordinal),
                JsonValueKind.Number => CompareNumbers(left, right),
                JsonValueKind.Array => CompareArrays(left, right),
                JsonValueKind.Object => CompareObjects(left, right),
                _ => false
            };
        }

        private static bool CompareNumbers(JsonElement left, JsonElement right)
        {
            var leftRaw = left.GetRawText();
            var rightRaw = right.GetRawText();
            if (string.Equals(leftRaw, rightRaw, StringComparison.Ordinal)) return true;
            if (left.TryGetDecimal(out var ld) && right.TryGetDecimal(out var rd)) return ld == rd;
            if (left.TryGetDouble(out var ldd) && right.TryGetDouble(out var rdd)) return ldd.Equals(rdd);
            return false;
        }

        private static bool CompareArrays(JsonElement left, JsonElement right)
        {
            var ll = left.GetArrayLength();
            if (ll != right.GetArrayLength()) return false;
            using var le = left.EnumerateArray();
            using var re = right.EnumerateArray();
            while (le.MoveNext() && re.MoveNext())
            {
                if (!DeepEquals(le.Current, re.Current)) return false;
            }
            return true;
        }

        private static bool CompareObjects(JsonElement left, JsonElement right)
        {
            var lc = 0; foreach (var _ in left.EnumerateObject()) lc++;
            var rc = 0; foreach (var _ in right.EnumerateObject()) rc++;
            if (lc != rc) return false;
            foreach (var lp in left.EnumerateObject())
            {
                if (!right.TryGetProperty(lp.Name, out var rv)) return false;
                if (!DeepEquals(lp.Value, rv)) return false;
            }
            return true;
        }
    }
}
