// Copyright (c) 2026 FormFinch VOF
// Licensed under the PolyForm Noncommercial License 1.0.0.
// See LICENSE file in the project root for full license information.
using System.IO.Compression;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using FormFinch.JsonSchemaValidation.CodeGeneration.Abstractions;
using FormFinch.JsonSchemaValidation.CodeGeneration.JavaScript;
using FormFinch.JsonSchemaValidation.CodeGeneration.TypeScript;
using Xunit;

namespace FormFinch.JsonSchemaValidation.CodeGenerator.Tests;

public sealed partial class OutputQualityReportTests
{
    private const string UpdateBaselineEnvironmentVariable = "JSV_UPDATE_CODEGEN_QUALITY_BASELINE";
    private const string PrintReportEnvironmentVariable = "JSV_PRINT_CODEGEN_QUALITY_REPORT";
    private const string RunReportEnvironmentVariable = "JSV_RUN_CODEGEN_QUALITY_REPORT";
    private static readonly UTF8Encoding Utf8NoBom = new(encoderShouldEmitUTF8Identifier: false);

    private readonly Xunit.Abstractions.ITestOutputHelper _testOutput;

    public OutputQualityReportTests(Xunit.Abstractions.ITestOutputHelper testOutput)
    {
        _testOutput = testOutput;
    }

#if NET8_0
    [Fact]
#else
    [Fact(Skip = "The output quality report is generated by net8.0 only to keep gzip baselines stable.")]
#endif
    [Trait("Category", "OutputQuality")]
    public async Task OutputQuality_GeneratesReportedOnlyJsAndTsMetrics()
    {
        if (!ShouldRunReport())
        {
            // Opt-in by design: this test runs the JS/TS code generator, executes tsc multiple times,
            // and writes report artifacts to the repo. It's not part of routine `dotnet test` runs.
            // To run it locally, follow the instructions in README.md (Local JS/TS Output Quality Report)
            // or set JSV_RUN_CODEGEN_QUALITY_REPORT=1 on the test invocation.
            _testOutput.WriteLine(
                "Codegen output quality report not generated: set JSV_RUN_CODEGEN_QUALITY_REPORT=1 to opt in.");
            return;
        }

        var repoRoot = FindRepositoryRoot();
        var reportDirectory = Path.Combine(repoRoot, "artifacts", "codegen-output-quality");
        var baselinePath = Path.Combine(repoRoot, "benchmarks", "codegen-output-quality-baseline.json");
        Directory.CreateDirectory(reportDirectory);

        var scenarios = LoadScenarios(repoRoot);
        var rows = new List<ReportRow>();
        var typeScriptRows = new List<GeneratedTargetRow>();

        foreach (var scenario in scenarios)
        {
            using var schemaDocument = JsonDocument.Parse(scenario.SchemaJson);
            var schema = schemaDocument.RootElement.Clone();

            var javaScriptRow = await GenerateTargetRowAsync(
                new JavaScriptCodeGenerationTarget(),
                new JavaScriptCodeGenerationOptions
                {
                    FormatAssertionEnabled = true,
                    ExternalSchemaDocuments = scenario.ExternalSchemaDocuments,
                    OutputHints = new CodeGenerationOutputHints { BaseFileName = scenario.Id }
                },
                schema,
                scenario.Id);
            rows.Add(javaScriptRow.Row);

            var typeScriptRow = await GenerateTargetRowAsync(
                new TypeScriptCodeGenerationTarget(),
                new TypeScriptCodeGenerationOptions
                {
                    FormatAssertionEnabled = true,
                    ExternalSchemaDocuments = scenario.ExternalSchemaDocuments,
                    OutputHints = new CodeGenerationOutputHints { BaseFileName = scenario.Id }
                },
                schema,
                scenario.Id);
            rows.Add(typeScriptRow.Row);
            if (typeScriptRow.Artifacts.Any(artifact => artifact.Role == GeneratedArtifactRole.Primary))
            {
                typeScriptRows.Add(typeScriptRow);
            }
        }

        ApplyTypeScriptStrictnessProfiles(typeScriptRows);

        var baseline = LoadBaseline(baselinePath);
        foreach (var row in rows)
        {
            row.BaselineDeltas = CalculateBaselineDeltas(row, baseline);
        }

        var qualitySummary = BuildQualitySummary(rows);

        var report = new ReportDocument
        {
            FormatVersion = 1,
            Notes =
            [
                "Reported-only output quality metrics for JavaScript and TypeScript code generation.",
                "All generated artifacts are normalized to UTF-8 text with LF line endings and one trailing newline before measurement.",
                "gzip_bytes is computed by System.IO.Compression.GZipStream with CompressionLevel.Optimal.",
                "function_count is a lightweight regex-based shape signal and can count function-like text in comments or strings.",
                "TypeScript strict_profiles compile every generated schema in one tsc invocation per profile, then attribute diagnostics back to each schema by source file. The per-profile entry under strict_profiles uses status 'failed' (with remediation 'generated-code') when the row's own .ts file has errors, status 'failed' (remediation 'runtime-types') when only the shared jsv-runtime.ts has errors, status 'unavailable' when tsc could not run, and status 'passed' otherwise. Strict-profile failures do not change the row's top-level status field, which only reflects the codegen step ('generated', 'unsupported', or 'generation-failed').",
                "quality_summary statuses: 'pass' = every scenario compiled cleanly under every strictness profile that ran. 'fail' = at least one scenario was rejected by codegen (e.g. status 'unsupported'), failed code generation, or failed a strictness profile. 'incomplete' = no failures, but at least one strictness profile could not run (e.g. tsc was not found). None of these imply anything about runtime validation correctness.",
                "baseline_deltas.status_change appears as 'old -> new' when a row's top-level status flips between baseline and current run (e.g. 'generated -> unsupported'); a flip out of 'generated' makes numeric deltas unreliable because no validator was emitted in the new run.",
                "baseline_deltas.strict_profile_changes lists per-profile status flips ('profile-name: old -> new') for TypeScript rows; the baseline file persists each profile's last status so regressions like 'no-unchecked-indexed-access: passed -> failed' surface alongside numeric deltas.",
                "Helper selection correctness is tracked separately by issue #46; this report measures footprint only.",
                "JS/TS deduplication decisions are tracked separately by issue #42.",
                "Lint/static-analysis signals are deferred to follow-up work."
            ],
            QualitySummary = qualitySummary,
            Rows = rows
        };

        var jsonOptions = CreateJsonOptions();
        var markdown = RenderMarkdown(report);
        File.WriteAllText(
            Path.Combine(reportDirectory, "codegen-output-quality.json"),
            JsonSerializer.Serialize(report, jsonOptions),
            Utf8NoBom);
        File.WriteAllText(
            Path.Combine(reportDirectory, "codegen-output-quality.md"),
            markdown,
            Utf8NoBom);

        if (ShouldPrintReport())
        {
            _testOutput.WriteLine("===== Codegen Output Quality Report =====");
            _testOutput.WriteLine(RenderConsole(report));
            _testOutput.WriteLine("===== End Report =====");
        }

        if (ShouldUpdateBaseline())
        {
            // Refuse to overwrite the baseline when any strict profile could not run (e.g. tsc was
            // unavailable). Persisting "unavailable" statuses would poison future delta comparisons
            // because the next run with tsc available would look like a regression.
            var unavailableProfiles = rows
                .Where(row => row.StrictProfiles is not null)
                .SelectMany(row => row.StrictProfiles!
                    .Where(profile => string.Equals(profile.Value.Status, "unavailable", StringComparison.Ordinal))
                    .Select(profile => $"{row.Target}/{row.Schema}:{profile.Key}"))
                .ToArray();
            if (unavailableProfiles.Length > 0)
            {
                throw new InvalidOperationException(
                    "Refusing to update the baseline because the report is incomplete. " +
                    "Strict profiles reported 'unavailable' (likely because tsc was not found). " +
                    $"Affected: {string.Join(", ", unavailableProfiles.Take(5))}{(unavailableProfiles.Length > 5 ? ", ..." : "")}. " +
                    "Install a TypeScript compiler 5.0+ and re-run with JSV_UPDATE_CODEGEN_QUALITY_BASELINE=1.");
            }

            Directory.CreateDirectory(Path.GetDirectoryName(baselinePath)!);
            var nextBaseline = BaselineDocument.FromRows(rows);
            File.WriteAllText(
                baselinePath,
                JsonSerializer.Serialize(nextBaseline, jsonOptions),
                Utf8NoBom);
        }

        var jsonReportPath = Path.Combine(reportDirectory, "codegen-output-quality.json");
        var markdownReportPath = Path.Combine(reportDirectory, "codegen-output-quality.md");
        Assert.True(File.Exists(jsonReportPath), "Expected the JSON report to be written.");
        Assert.True(File.Exists(markdownReportPath), "Expected the Markdown report to be written.");
        Assert.NotEmpty(rows);
        Assert.Contains(rows, row => row.Target == "javascript");
        Assert.Contains(rows, row => row.Target == "typescript");
        Assert.NotEmpty(qualitySummary);
        Assert.All(qualitySummary, entry =>
        {
            Assert.Contains(entry.Status, new[] { "pass", "fail", "incomplete" });
            Assert.Equal(group(rows, entry.Target),
                entry.PassingScenarioCount + entry.FailingScenarioCount + entry.IncompleteScenarioCount);
        });
        Assert.Contains("Quality Summary", markdown);
        Assert.Contains("Per-Schema Metrics", markdown);
        Assert.All(rows.Where(row => row.Target == "typescript" && row.Status == "generated"),
            row => Assert.NotNull(row.StrictProfiles));

        static int group(IReadOnlyList<ReportRow> all, string target) =>
            all.Count(row => string.Equals(row.Target, target, StringComparison.Ordinal));
    }

    private static async Task<GeneratedTargetRow> GenerateTargetRowAsync(
        ICodeGenerationTarget target,
        CodeGenerationOptions options,
        JsonElement schema,
        string scenarioId)
    {
        var request = new CodeGenerationRequest
        {
            Schema = schema,
            Options = options
        };

        var capability = await target.GetCapabilitiesAsync(request);
        if (!capability.CanGenerate)
        {
            return new GeneratedTargetRow(new ReportRow
            {
                Target = target.Descriptor.Id,
                Schema = scenarioId,
                Status = "unsupported",
                Diagnostics = MapDiagnostics(capability.Diagnostics),
                Helpers = [],
                StrictProfiles = target.Descriptor.Id == "typescript" ? new Dictionary<string, StrictProfileReport>() : null
            }, []);
        }

        var generation = await target.GenerateAsync(request);
        if (!generation.Success)
        {
            return new GeneratedTargetRow(new ReportRow
            {
                Target = target.Descriptor.Id,
                Schema = scenarioId,
                Status = "generation-failed",
                Diagnostics = MapDiagnostics(generation.Diagnostics),
                Helpers = [],
                StrictProfiles = target.Descriptor.Id == "typescript" ? new Dictionary<string, StrictProfileReport>() : null
            }, []);
        }

        var artifacts = generation.Artifacts
            .OrderByDescending(artifact => artifact.Role == GeneratedArtifactRole.Primary)
            .ThenBy(artifact => artifact.RelativePath, StringComparer.Ordinal)
            .Select(artifact => new NormalizedArtifact(
                artifact.RelativePath,
                artifact.Kind,
                artifact.Role,
                NormalizeSource(artifact.Content)))
            .ToArray();

        var primaryContent = string.Concat(artifacts
            .Where(artifact => artifact.Role == GeneratedArtifactRole.Primary)
            .Select(artifact => artifact.Content));
        var supportContent = string.Concat(artifacts
            .Where(artifact => artifact.Role != GeneratedArtifactRole.Primary)
            .Select(artifact => artifact.Content));
        var helpers = ExtractRuntimeImports(primaryContent).Order(StringComparer.Ordinal).ToArray();

        // Sum gzip-compressed sizes per artifact role rather than gzipping concatenated content,
        // because the JS/TS targets emit primary and support as separate files and that is what
        // users actually ship. Concatenated compression would benefit from cross-file dedup that
        // does not exist on disk.
        var gzipBytes = CountGzipBytes(primaryContent) + (supportContent.Length > 0 ? CountGzipBytes(supportContent) : 0);

        return new GeneratedTargetRow(new ReportRow
        {
            Target = target.Descriptor.Id,
            Schema = scenarioId,
            Status = "generated",
            Diagnostics = [],
            ValidatorBytes = CountUtf8Bytes(primaryContent),
            RuntimeBytes = CountUtf8Bytes(supportContent),
            TotalBytes = CountUtf8Bytes(primaryContent) + CountUtf8Bytes(supportContent),
            GzipBytes = gzipBytes,
            Loc = CountPhysicalLines(primaryContent),
            FunctionCount = CountFunctions(primaryContent),
            MaxIndentationDepth = CalculateMaxIndentationDepth(primaryContent),
            HelperCount = helpers.Length,
            Helpers = helpers,
            StrictProfiles = target.Descriptor.Id == "typescript" ? new Dictionary<string, StrictProfileReport>() : null
        }, artifacts);
    }

    private static void ApplyTypeScriptStrictnessProfiles(IReadOnlyList<GeneratedTargetRow> typeScriptRows)
    {
        foreach (var row in typeScriptRows)
        {
            row.Row.StrictProfiles ??= new Dictionary<string, StrictProfileReport>();
        }

        if (typeScriptRows.Count == 0)
        {
            return;
        }

        if (!TypeScriptCompiler.IsAvailable())
        {
            foreach (var row in typeScriptRows)
            {
                foreach (var profile in GetStrictnessProfiles())
                {
                    row.Row.StrictProfiles![profile.Name] = new StrictProfileReport
                    {
                        Status = "unavailable",
                        Remediation = "unknown",
                        Diagnostics = ["TypeScript compiler 'tsc' is not available."]
                    };
                }
            }
            return;
        }

        var tempRoot = Path.Combine(Path.GetTempPath(), "jsv-output-quality-ts-" + Guid.NewGuid().ToString("N"));
        var sourceRoot = Path.Combine(tempRoot, "src");
        Directory.CreateDirectory(sourceRoot);
        try
        {
            var runtimePath = Path.Combine(sourceRoot, TsRuntime.FileName);
            File.WriteAllText(runtimePath, NormalizeSource(TsRuntime.GetSource()), Utf8NoBom);

            var sourcePaths = new List<string> { runtimePath };
            var rowSourcePaths = new Dictionary<GeneratedTargetRow, string>();
            foreach (var generatedRow in typeScriptRows)
            {
                // typeScriptRows is filtered upstream to only contain rows with a primary artifact,
                // so Single() is the right invariant here.
                var primaryArtifact = generatedRow.Artifacts.Single(artifact => artifact.Role == GeneratedArtifactRole.Primary);
                var sourcePath = Path.Combine(sourceRoot, $"{generatedRow.Row.Schema}.ts");
                File.WriteAllText(sourcePath, primaryArtifact.Content, Utf8NoBom);
                sourcePaths.Add(sourcePath);
                rowSourcePaths[generatedRow] = sourcePath;
            }

            var relativeSourcePaths = sourcePaths
                .Select(path => Path.GetRelativePath(tempRoot, path))
                .ToArray();
            foreach (var profile in GetStrictnessProfiles())
            {
                var outputDirectory = Path.Combine(tempRoot, "out", profile.Name);
                var compileResult = TypeScriptCompiler.Compile(
                    relativeSourcePaths,
                    outputDirectory,
                    ecmaScriptTarget: "ES2020",
                    options: profile.Options,
                    timeoutMilliseconds: 240_000,
                    workingDirectory: tempRoot);
                var attributedDiagnostics = AttributeTscDiagnostics(compileResult, tempRoot);

                foreach (var (generatedRow, sourcePath) in rowSourcePaths)
                {
                    var rowFileName = Path.GetFileName(sourcePath);
                    var rowDiagnostics = attributedDiagnostics.GetValueOrDefault(rowFileName, []);
                    var runtimeDiagnostics = attributedDiagnostics.GetValueOrDefault(TsRuntime.FileName, []);

                    string status;
                    string? remediation;
                    if (rowDiagnostics.Count > 0)
                    {
                        status = "failed";
                        remediation = "generated-code";
                    }
                    else if (runtimeDiagnostics.Count > 0)
                    {
                        status = "failed";
                        remediation = "runtime-types";
                    }
                    else if (!compileResult.Success)
                    {
                        status = "failed";
                        remediation = "unknown";
                    }
                    else
                    {
                        status = "passed";
                        remediation = null;
                    }

                    var rowReport = new List<string>();
                    rowReport.AddRange(rowDiagnostics);
                    rowReport.AddRange(runtimeDiagnostics.Select(line => "[shared-runtime] " + line));

                    generatedRow.Row.StrictProfiles![profile.Name] = new StrictProfileReport
                    {
                        Status = status,
                        Remediation = remediation,
                        Diagnostics = TruncateDiagnostics(rowReport)
                    };
                }
            }
        }
        finally
        {
            try { Directory.Delete(tempRoot, recursive: true); } catch { /* best effort */ }
        }
    }

    private static IReadOnlyDictionary<string, IReadOnlyList<string>> AttributeTscDiagnostics(
        TypeScriptCompilationResult result,
        string tempRoot)
    {
        var attributed = new Dictionary<string, List<string>>(StringComparer.Ordinal);
        if (result.Success)
        {
            return attributed.ToDictionary(
                pair => pair.Key,
                pair => (IReadOnlyList<string>)pair.Value,
                StringComparer.Ordinal);
        }

        var rawText = string.Concat(
            string.IsNullOrWhiteSpace(result.StandardError) ? "" : result.StandardError + "\n",
            string.IsNullOrWhiteSpace(result.StandardOutput) ? "" : result.StandardOutput);
        var normalized = NormalizeDiagnosticText(rawText, tempRoot);

        string? currentFileKey = null;
        foreach (var line in normalized.Split('\n'))
        {
            var trimmed = line.TrimEnd();
            if (trimmed.Length == 0)
            {
                continue;
            }

            var match = TscDiagnosticHeaderRegex().Match(trimmed);
            if (match.Success)
            {
                var path = match.Groups["path"].Value;
                currentFileKey = Path.GetFileName(path);
            }

            if (currentFileKey is null)
            {
                continue;
            }

            if (!attributed.TryGetValue(currentFileKey, out var bucket))
            {
                bucket = new List<string>();
                attributed[currentFileKey] = bucket;
            }
            bucket.Add(trimmed);
        }

        return attributed.ToDictionary(
            pair => pair.Key,
            pair => (IReadOnlyList<string>)pair.Value,
            StringComparer.Ordinal);
    }

    private static IReadOnlyList<string> TruncateDiagnostics(IReadOnlyList<string> lines)
    {
        const int maxLines = 80;
        if (lines.Count <= maxLines)
        {
            return lines.ToArray();
        }

        return lines.Take(maxLines)
            .Append($"... truncated {lines.Count - maxLines} additional diagnostic lines")
            .ToArray();
    }

    private static IReadOnlyList<Scenario> LoadScenarios(string repoRoot)
    {
        return
        [
            new("primitive-string", """{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"string"}"""),
            new("integer-constraints", """{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"integer","minimum":3,"multipleOf":2}"""),
            new("object-required-additional-properties", """
                {
                  "$schema": "https://json-schema.org/draft/2020-12/schema",
                  "type": "object",
                  "required": ["name"],
                  "properties": {
                    "name": { "type": "string" },
                    "age": { "type": "integer", "minimum": 0 }
                  },
                  "additionalProperties": false
                }
                """),
            new("enum-const", """{"$schema":"https://json-schema.org/draft/2020-12/schema","enum":["red","green",3],"const":"red"}"""),
            new("format-assertion", """{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"string","format":"email"}"""),
            new("external-ref", """{"$schema":"https://json-schema.org/draft/2020-12/schema","$ref":"https://example.com/schemas/external-string"}""",
                new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["https://example.com/schemas/external-string"] =
                        """{"$id":"https://example.com/schemas/external-string","type":"string","minLength":2}"""
                }),
            new("dynamic-ref", """
                {
                  "$schema": "https://json-schema.org/draft/2020-12/schema",
                  "$dynamicAnchor": "node",
                  "type": "object",
                  "properties": {
                    "value": { "type": "string" },
                    "child": { "$dynamicRef": "#node" }
                  }
                }
                """),
            new("unevaluated", """
                {
                  "$schema": "https://json-schema.org/draft/2020-12/schema",
                  "type": "object",
                  "properties": {
                    "items": {
                      "type": "array",
                      "prefixItems": [{ "type": "string" }],
                      "unevaluatedItems": false
                    }
                  },
                  "unevaluatedProperties": false
                }
                """),
            new("production-package-json", File.ReadAllText(Path.Combine(repoRoot, "JsonSchemaValidationTests", "ProductionSchemas", "PackageJson", "schema.json"))),
            new("production-tsconfig", File.ReadAllText(Path.Combine(repoRoot, "JsonSchemaValidationTests", "ProductionSchemas", "TsConfig", "schema.json"))),
            new("production-github-workflow", File.ReadAllText(Path.Combine(repoRoot, "JsonSchemaValidationTests", "ProductionSchemas", "GithubWorkflow", "schema.json")))
        ];
    }

    private static IReadOnlyDictionary<string, BaselineRow> LoadBaseline(string baselinePath)
    {
        if (!File.Exists(baselinePath))
        {
            return new Dictionary<string, BaselineRow>(StringComparer.Ordinal);
        }

        var baseline = JsonSerializer.Deserialize<BaselineDocument>(
            File.ReadAllText(baselinePath, Utf8NoBom),
            CreateJsonOptions());
        return baseline?.Rows.ToDictionary(row => GetBaselineKey(row.Target, row.Schema), StringComparer.Ordinal)
            ?? new Dictionary<string, BaselineRow>(StringComparer.Ordinal);
    }

    private static MetricDeltas? CalculateBaselineDeltas(ReportRow row, IReadOnlyDictionary<string, BaselineRow> baseline)
    {
        if (!baseline.TryGetValue(GetBaselineKey(row.Target, row.Schema), out var baselineRow))
        {
            return null;
        }

        var statusChange = string.Equals(row.Status, baselineRow.Status, StringComparison.Ordinal)
            ? null
            : $"{baselineRow.Status} -> {row.Status}";

        return new MetricDeltas
        {
            StatusChange = statusChange,
            StrictProfileChanges = ComputeStrictProfileChanges(row.StrictProfiles, baselineRow.StrictProfiles),
            ValidatorBytes = Subtract(row.ValidatorBytes, baselineRow.ValidatorBytes),
            RuntimeBytes = Subtract(row.RuntimeBytes, baselineRow.RuntimeBytes),
            TotalBytes = Subtract(row.TotalBytes, baselineRow.TotalBytes),
            GzipBytes = Subtract(row.GzipBytes, baselineRow.GzipBytes),
            Loc = Subtract(row.Loc, baselineRow.Loc),
            FunctionCount = Subtract(row.FunctionCount, baselineRow.FunctionCount),
            MaxIndentationDepth = Subtract(row.MaxIndentationDepth, baselineRow.MaxIndentationDepth),
            HelperCount = Subtract(row.HelperCount, baselineRow.HelperCount)
        };
    }

    private static IReadOnlyList<string>? ComputeStrictProfileChanges(
        IReadOnlyDictionary<string, StrictProfileReport>? current,
        IReadOnlyDictionary<string, string>? baseline)
    {
        // Old baselines (pre-strict-profile baseline support) have null here, in which case there
        // is no flip to surface — leave the field unset rather than fabricating a "missing -> X" entry.
        if (baseline is null || baseline.Count == 0)
        {
            return null;
        }

        var changes = new List<string>();
        var profileNames = new SortedSet<string>(StringComparer.Ordinal);
        if (current is not null)
        {
            foreach (var name in current.Keys)
            {
                profileNames.Add(name);
            }
        }
        foreach (var name in baseline.Keys)
        {
            profileNames.Add(name);
        }

        foreach (var name in profileNames)
        {
            var oldStatus = baseline.TryGetValue(name, out var b) ? b : "(missing)";
            var newStatus = current is not null && current.TryGetValue(name, out var c) ? c.Status : "(missing)";
            if (!string.Equals(oldStatus, newStatus, StringComparison.Ordinal))
            {
                changes.Add($"{name}: {oldStatus} -> {newStatus}");
            }
        }

        return changes.Count == 0 ? null : changes;
    }

    private static string NormalizeSource(string source)
    {
        var normalized = source.Replace("\r\n", "\n", StringComparison.Ordinal).Replace('\r', '\n');
        return normalized.TrimEnd('\n') + "\n";
    }

    private static int CountUtf8Bytes(string source) => Utf8NoBom.GetByteCount(source);

    private static int CountPhysicalLines(string source) => source.Length == 0 ? 0 : source.Split('\n').Length - 1;

    private static int CountFunctions(string source)
    {
        return FunctionRegex().Matches(source).Count + ArrowFunctionRegex().Matches(source).Count;
    }

    private static int CalculateMaxIndentationDepth(string source)
    {
        var maxColumns = 0;
        foreach (var line in source.Split('\n'))
        {
            var columns = 0;
            foreach (var c in line)
            {
                if (c == ' ')
                {
                    columns++;
                }
                else if (c == '\t')
                {
                    columns += 4;
                }
                else
                {
                    break;
                }
            }

            maxColumns = Math.Max(maxColumns, columns);
        }

        return maxColumns / 2;
    }

    private static int CountGzipBytes(string source)
    {
        var bytes = Utf8NoBom.GetBytes(source);
        using var memoryStream = new MemoryStream();
        using (var gzipStream = new GZipStream(memoryStream, CompressionLevel.Optimal, leaveOpen: true))
        {
            gzipStream.Write(bytes, 0, bytes.Length);
        }

        return checked((int)memoryStream.Length);
    }

    private static IReadOnlyList<string> ExtractRuntimeImports(string source)
    {
        var helpers = new SortedSet<string>(StringComparer.Ordinal);
        foreach (Match match in RuntimeImportRegex().Matches(source))
        {
            var names = match.Groups["names"].Value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            foreach (var name in names)
            {
                var cleaned = name;
                if (cleaned.StartsWith("type ", StringComparison.Ordinal))
                {
                    // Per-specifier `type X` is a compile-time-only import; skip it.
                    continue;
                }

                var asIndex = cleaned.IndexOf(" as ", StringComparison.Ordinal);
                if (asIndex >= 0)
                {
                    cleaned = cleaned[..asIndex].Trim();
                }

                if (cleaned.Length > 0)
                {
                    helpers.Add(cleaned);
                }
            }
        }

        return helpers.ToArray();
    }

    private static string RenderConsole(ReportDocument report)
    {
        var sb = new StringBuilder();
        sb.AppendLine("Codegen Output Quality");
        sb.AppendLine("======================");
        sb.AppendLine();
        sb.AppendLine("Quality Summary");
        sb.AppendLine("---------------");
        sb.AppendLine("FAIL       = at least one scenario is rejected by codegen (e.g. unsupported), fails code generation, or fails a strictness profile.");
        sb.AppendLine("INCOMPLETE = no failures, but at least one strictness profile could not run (e.g. tsc unavailable).");
        sb.AppendLine("PASS       = every scenario compiled cleanly under every strictness profile that ran.");
        sb.AppendLine("None of these statuses imply anything about runtime validation correctness.");
        sb.AppendLine();

        var summaryHeaders = new[] { "target", "status", "pass", "fail", "incomplete", "failing strict profiles", "incomplete strict profiles" };
        var summaryRows = report.QualitySummary
            .OrderBy(entry => entry.Target, StringComparer.Ordinal)
            .Select(entry => new[]
            {
                entry.Target,
                entry.Status.ToUpperInvariant(),
                entry.PassingScenarioCount.ToString(System.Globalization.CultureInfo.InvariantCulture),
                entry.FailingScenarioCount.ToString(System.Globalization.CultureInfo.InvariantCulture),
                entry.IncompleteScenarioCount.ToString(System.Globalization.CultureInfo.InvariantCulture),
                entry.FailingProfiles.Count == 0 ? "-" : string.Join(", ", entry.FailingProfiles),
                entry.IncompleteProfiles.Count == 0 ? "-" : string.Join(", ", entry.IncompleteProfiles)
            })
            .ToArray();
        AppendPlainTable(sb, summaryHeaders, summaryRows, rightAlignColumns: [2, 3, 4]);
        sb.AppendLine();

        sb.AppendLine("Per-Schema Metrics");
        sb.AppendLine("------------------");
        var metricHeaders = new[] { "target", "schema", "status", "validator", "runtime", "total", "gzip", "loc", "fns", "depth", "helpers", "deltas" };
        var metricRows = report.Rows
            .OrderBy(row => row.Target, StringComparer.Ordinal)
            .ThenBy(row => row.Schema, StringComparer.Ordinal)
            .Select(row => new[]
            {
                row.Target,
                row.Schema,
                row.Status,
                FormatNullable(row.ValidatorBytes),
                FormatNullable(row.RuntimeBytes),
                FormatNullable(row.TotalBytes),
                FormatNullable(row.GzipBytes),
                FormatNullable(row.Loc),
                FormatNullable(row.FunctionCount),
                FormatNullable(row.MaxIndentationDepth),
                FormatNullable(row.HelperCount),
                FormatDeltas(row.BaselineDeltas)
            })
            .ToArray();
        AppendPlainTable(sb, metricHeaders, metricRows, rightAlignColumns: [3, 4, 5, 6, 7, 8, 9, 10]);
        sb.AppendLine();

        var tsRows = report.Rows
            .Where(row => row.StrictProfiles is { Count: > 0 })
            .OrderBy(row => row.Schema, StringComparer.Ordinal)
            .ToArray();
        if (tsRows.Length > 0)
        {
            sb.AppendLine("TypeScript Strictness Detail");
            sb.AppendLine("----------------------------");
            var profileNames = tsRows
                .SelectMany(row => row.StrictProfiles!.Keys)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(name => name, StringComparer.Ordinal)
                .ToArray();
            var strictHeaders = new[] { "schema" }.Concat(profileNames).ToArray();
            var strictRows = tsRows.Select(row =>
            {
                var cells = new string[strictHeaders.Length];
                cells[0] = row.Schema;
                for (var i = 0; i < profileNames.Length; i++)
                {
                    cells[i + 1] = row.StrictProfiles!.TryGetValue(profileNames[i], out var profile)
                        ? profile.Status
                        : "-";
                }
                return cells;
            }).ToArray();
            AppendPlainTable(sb, strictHeaders, strictRows, rightAlignColumns: []);
            sb.AppendLine();
        }

        sb.AppendLine("Notes");
        sb.AppendLine("-----");
        foreach (var note in report.Notes)
        {
            sb.AppendLine("- " + note);
        }

        return sb.ToString();
    }

    private static void AppendPlainTable(
        StringBuilder sb,
        IReadOnlyList<string> headers,
        IReadOnlyList<string[]> rows,
        IReadOnlyList<int> rightAlignColumns)
    {
        var widths = new int[headers.Count];
        for (var i = 0; i < headers.Count; i++)
        {
            widths[i] = headers[i].Length;
        }
        foreach (var row in rows)
        {
            for (var i = 0; i < headers.Count; i++)
            {
                if (row[i].Length > widths[i])
                {
                    widths[i] = row[i].Length;
                }
            }
        }

        AppendPlainTableRow(sb, headers.ToArray(), widths, rightAlignColumns);
        var separator = new string[headers.Count];
        for (var i = 0; i < headers.Count; i++)
        {
            separator[i] = new string('-', widths[i]);
        }
        AppendPlainTableRow(sb, separator, widths, []);
        foreach (var row in rows)
        {
            AppendPlainTableRow(sb, row, widths, rightAlignColumns);
        }
    }

    private static void AppendPlainTableRow(
        StringBuilder sb,
        string[] cells,
        int[] widths,
        IReadOnlyList<int> rightAlignColumns)
    {
        for (var i = 0; i < cells.Length; i++)
        {
            if (i > 0)
            {
                sb.Append("  ");
            }
            sb.Append(rightAlignColumns.Contains(i) ? cells[i].PadLeft(widths[i]) : cells[i].PadRight(widths[i]));
        }
        sb.AppendLine();
    }

    private static string RenderMarkdown(ReportDocument report)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Codegen Output Quality");
        sb.AppendLine();

        sb.AppendLine("## Quality Summary");
        sb.AppendLine();
        sb.AppendLine("Headline status per target. **FAIL** = at least one scenario is rejected by codegen (e.g. `unsupported`), fails code generation, or fails a strictness profile. **INCOMPLETE** = no failures, but at least one strictness profile could not run (e.g. `tsc` unavailable). **PASS** = every scenario compiled cleanly under every strictness profile that ran. None of these statuses imply anything about runtime validation correctness.");
        sb.AppendLine();
        sb.AppendLine("| target | status | passing scenarios | failing scenarios | incomplete scenarios | failing strict profiles | incomplete strict profiles |");
        sb.AppendLine("| --- | --- | ---: | ---: | ---: | --- | --- |");
        foreach (var entry in report.QualitySummary.OrderBy(entry => entry.Target, StringComparer.Ordinal))
        {
            var failingProfiles = entry.FailingProfiles.Count == 0
                ? "—"
                : string.Join(", ", entry.FailingProfiles);
            var incompleteProfiles = entry.IncompleteProfiles.Count == 0
                ? "—"
                : string.Join(", ", entry.IncompleteProfiles);
            sb.Append("| ");
            sb.Append(EscapeMarkdown(entry.Target));
            sb.Append(" | ");
            sb.Append(entry.Status.ToUpperInvariant());
            sb.Append(" | ");
            sb.Append(entry.PassingScenarioCount);
            sb.Append(" | ");
            sb.Append(entry.FailingScenarioCount);
            sb.Append(" | ");
            sb.Append(entry.IncompleteScenarioCount);
            sb.Append(" | ");
            sb.Append(EscapeMarkdown(failingProfiles));
            sb.Append(" | ");
            sb.Append(EscapeMarkdown(incompleteProfiles));
            sb.AppendLine(" |");
        }

        sb.AppendLine();
        sb.AppendLine("## Notes");
        sb.AppendLine();
        foreach (var note in report.Notes)
        {
            sb.AppendLine($"- {note}");
        }

        sb.AppendLine();
        sb.AppendLine("## Per-Schema Metrics");
        sb.AppendLine();
        sb.AppendLine("| target | schema | status | validator bytes | runtime bytes | total bytes | gzip bytes | LOC | functions | max depth | helpers | deltas |");
        sb.AppendLine("| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |");
        foreach (var row in report.Rows.OrderBy(row => row.Target, StringComparer.Ordinal).ThenBy(row => row.Schema, StringComparer.Ordinal))
        {
            sb.Append("| ");
            sb.Append(EscapeMarkdown(row.Target));
            sb.Append(" | ");
            sb.Append(EscapeMarkdown(row.Schema));
            sb.Append(" | ");
            sb.Append(EscapeMarkdown(row.Status));
            sb.Append(" | ");
            sb.Append(FormatNullable(row.ValidatorBytes));
            sb.Append(" | ");
            sb.Append(FormatNullable(row.RuntimeBytes));
            sb.Append(" | ");
            sb.Append(FormatNullable(row.TotalBytes));
            sb.Append(" | ");
            sb.Append(FormatNullable(row.GzipBytes));
            sb.Append(" | ");
            sb.Append(FormatNullable(row.Loc));
            sb.Append(" | ");
            sb.Append(FormatNullable(row.FunctionCount));
            sb.Append(" | ");
            sb.Append(FormatNullable(row.MaxIndentationDepth));
            sb.Append(" | ");
            sb.Append(FormatNullable(row.HelperCount));
            sb.Append(" | ");
            sb.Append(EscapeMarkdown(FormatDeltas(row.BaselineDeltas)));
            sb.AppendLine(" |");
        }

        sb.AppendLine();
        sb.AppendLine("## TypeScript Strictness Detail");
        sb.AppendLine();
        sb.AppendLine("Each row shows whether the generated TypeScript for a scenario compiles under each strictness profile. `failed` indicates `tsc` reported errors under that profile.");
        sb.AppendLine();
        foreach (var row in report.Rows.Where(row => row.StrictProfiles is { Count: > 0 }).OrderBy(row => row.Schema, StringComparer.Ordinal))
        {
            sb.AppendLine($"- `{row.Schema}`: {string.Join(", ", row.StrictProfiles!.Select(profile => $"{profile.Key}={profile.Value.Status}"))}");
        }

        return sb.ToString();
    }

    private static IReadOnlyList<QualitySummaryEntry> BuildQualitySummary(IReadOnlyList<ReportRow> rows)
    {
        var entries = new List<QualitySummaryEntry>();
        foreach (var group in rows.GroupBy(row => row.Target, StringComparer.Ordinal).OrderBy(group => group.Key, StringComparer.Ordinal))
        {
            var passingScenarios = 0;
            var failingScenarios = 0;
            var incompleteScenarios = 0;
            var failingProfiles = new SortedSet<string>(StringComparer.Ordinal);
            var incompleteProfiles = new SortedSet<string>(StringComparer.Ordinal);
            var hasIncomplete = false;

            foreach (var row in group)
            {
                var rowFailed = false;
                var rowIncomplete = false;

                if (row.Status != "generated")
                {
                    rowFailed = true;
                    failingProfiles.Add($"codegen:{row.Status}");
                }

                if (row.StrictProfiles is { Count: > 0 })
                {
                    foreach (var profile in row.StrictProfiles)
                    {
                        switch (profile.Value.Status)
                        {
                            case "failed":
                                rowFailed = true;
                                failingProfiles.Add(profile.Key);
                                break;
                            case "skipped":
                                rowFailed = true;
                                failingProfiles.Add($"{profile.Key}:skipped");
                                break;
                            case "unavailable":
                                rowIncomplete = true;
                                hasIncomplete = true;
                                incompleteProfiles.Add($"{profile.Key}:tsc-unavailable");
                                break;
                        }
                    }
                }

                if (rowFailed)
                {
                    failingScenarios++;
                }
                else if (rowIncomplete)
                {
                    incompleteScenarios++;
                }
                else
                {
                    passingScenarios++;
                }
            }

            string status;
            if (failingScenarios > 0)
            {
                status = "fail";
            }
            else if (hasIncomplete)
            {
                status = "incomplete";
            }
            else
            {
                status = "pass";
            }

            entries.Add(new QualitySummaryEntry
            {
                Target = group.Key,
                Status = status,
                PassingScenarioCount = passingScenarios,
                FailingScenarioCount = failingScenarios,
                IncompleteScenarioCount = incompleteScenarios,
                FailingProfiles = failingProfiles.ToArray(),
                IncompleteProfiles = incompleteProfiles.ToArray()
            });
        }

        return entries;
    }

    private static IReadOnlyList<StrictnessProfile> GetStrictnessProfiles()
    {
        return
        [
            new("strict-no-implicit-any", new TypeScriptCompilerOptions { Strict = true, NoImplicitAny = true }),
            new("no-unchecked-indexed-access", new TypeScriptCompilerOptions { Strict = true, NoImplicitAny = true, NoUncheckedIndexedAccess = true }),
            new("exact-optional-property-types", new TypeScriptCompilerOptions { Strict = true, NoImplicitAny = true, ExactOptionalPropertyTypes = true }),
            new("combined-extra-strict", new TypeScriptCompilerOptions
            {
                Strict = true,
                NoImplicitAny = true,
                NoUncheckedIndexedAccess = true,
                ExactOptionalPropertyTypes = true
            })
        ];
    }

    private static IReadOnlyList<DiagnosticReport> MapDiagnostics(IReadOnlyList<CodeGenerationDiagnostic> diagnostics)
    {
        return diagnostics.Select(diagnostic => new DiagnosticReport
        {
            Severity = diagnostic.Severity.ToString(),
            Code = diagnostic.Code,
            Message = diagnostic.Message,
            JsonPointer = diagnostic.JsonPointer
        }).ToArray();
    }

    private static string NormalizeDiagnosticText(string text, string? tempRoot)
    {
        var normalized = text.Replace("\r\n", "\n", StringComparison.Ordinal).Replace('\r', '\n');
        if (!string.IsNullOrWhiteSpace(tempRoot))
        {
            normalized = normalized
                .Replace(tempRoot, "<temp>", StringComparison.OrdinalIgnoreCase)
                .Replace(tempRoot.Replace('\\', '/'), "<temp>", StringComparison.OrdinalIgnoreCase);
        }

        return normalized.Trim();
    }

    private static JsonSerializerOptions CreateJsonOptions()
    {
        return new JsonSerializerOptions
        {
            WriteIndented = true,
            PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower
        };
    }

    private static bool ShouldUpdateBaseline()
    {
        var value = Environment.GetEnvironmentVariable(UpdateBaselineEnvironmentVariable);
        return string.Equals(value, "1", StringComparison.Ordinal) ||
               string.Equals(value, "true", StringComparison.OrdinalIgnoreCase);
    }

    private static bool ShouldPrintReport()
    {
        var value = Environment.GetEnvironmentVariable(PrintReportEnvironmentVariable);
        return string.Equals(value, "1", StringComparison.Ordinal) ||
               string.Equals(value, "true", StringComparison.OrdinalIgnoreCase);
    }

    private static bool ShouldRunReport()
    {
        var value = Environment.GetEnvironmentVariable(RunReportEnvironmentVariable);
        return string.Equals(value, "1", StringComparison.Ordinal) ||
               string.Equals(value, "true", StringComparison.OrdinalIgnoreCase);
    }

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory != null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "JsonSchemaValidationSolution.slnx")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new InvalidOperationException("Could not locate repository root.");
    }

    private static string GetBaselineKey(string target, string schema) => target + ":" + schema;

    private static int? Subtract(int? actual, int? baseline)
    {
        return actual.HasValue && baseline.HasValue ? actual.Value - baseline.Value : null;
    }

    private static string FormatNullable(int? value) => value?.ToString(System.Globalization.CultureInfo.InvariantCulture) ?? "";

    private static string FormatDeltas(MetricDeltas? deltas)
    {
        if (deltas == null)
        {
            return "";
        }

        var hasNumericDelta = deltas.TotalBytes.HasValue || deltas.GzipBytes.HasValue || deltas.Loc.HasValue;
        var hasProfileChanges = deltas.StrictProfileChanges is { Count: > 0 };
        if (deltas.StatusChange is null && !hasNumericDelta && !hasProfileChanges)
        {
            return "";
        }

        var parts = new List<string>();
        if (deltas.StatusChange is { } statusChange)
        {
            // Highlight status flips (e.g. generated -> unsupported) since metric deltas alone
            // would not surface a regression that drops a row out of code generation.
            parts.Add($"status {statusChange}");
        }

        if (hasNumericDelta)
        {
            parts.Add($"total {FormatDelta(deltas.TotalBytes)}, gzip {FormatDelta(deltas.GzipBytes)}, loc {FormatDelta(deltas.Loc)}");
        }

        if (hasProfileChanges)
        {
            parts.Add($"strict_profiles {string.Join(", ", deltas.StrictProfileChanges!)}");
        }

        return string.Join("; ", parts);
    }

    private static string FormatDelta(int? value)
    {
        if (!value.HasValue)
        {
            return "";
        }

        return value.Value >= 0 ? "+" + value.Value.ToString(System.Globalization.CultureInfo.InvariantCulture) : value.Value.ToString(System.Globalization.CultureInfo.InvariantCulture);
    }

    private static string EscapeMarkdown(string value) => value.Replace("|", "\\|", StringComparison.Ordinal);

    [GeneratedRegex(@"\bfunction\b", RegexOptions.CultureInvariant)]
    private static partial Regex FunctionRegex();

    [GeneratedRegex(@"=>", RegexOptions.CultureInvariant)]
    private static partial Regex ArrowFunctionRegex();

    // Match value-only `import { ... } from "...jsv-runtime.js"` (no `import type` form).
    // The per-name parser skips specifiers prefixed with `type` so mixed imports such as
    // `import { type JsonValue, validate } from "..."` only count `validate`.
    [GeneratedRegex(@"import\s+\{\s*(?<names>[^}]+)\s*\}\s+from\s+[""'][^""']*jsv-runtime\.js[""']", RegexOptions.CultureInvariant)]
    private static partial Regex RuntimeImportRegex();

    [GeneratedRegex(@"^(?<path>.+\.ts)\(\d+,\d+\):\s+error\s+TS\d+:", RegexOptions.CultureInvariant)]
    private static partial Regex TscDiagnosticHeaderRegex();

    private sealed record Scenario(
        string Id,
        string SchemaJson,
        IReadOnlyDictionary<string, string>? ExternalSchemaDocuments = null);

    private sealed record GeneratedTargetRow(ReportRow Row, IReadOnlyList<NormalizedArtifact> Artifacts);

    private sealed record NormalizedArtifact(
        string RelativePath,
        GeneratedArtifactKind Kind,
        GeneratedArtifactRole Role,
        string Content);

    private sealed record StrictnessProfile(string Name, TypeScriptCompilerOptions Options);

    private sealed class ReportDocument
    {
        public int FormatVersion { get; init; }
        public IReadOnlyList<string> Notes { get; init; } = [];
        public IReadOnlyList<QualitySummaryEntry> QualitySummary { get; init; } = [];
        public IReadOnlyList<ReportRow> Rows { get; init; } = [];
    }

    private sealed class QualitySummaryEntry
    {
        public required string Target { get; init; }
        public required string Status { get; init; }
        public int PassingScenarioCount { get; init; }
        public int FailingScenarioCount { get; init; }
        public int IncompleteScenarioCount { get; init; }
        public IReadOnlyList<string> FailingProfiles { get; init; } = [];
        public IReadOnlyList<string> IncompleteProfiles { get; init; } = [];
    }

    private sealed class ReportRow
    {
        public required string Target { get; init; }
        public required string Schema { get; init; }
        public required string Status { get; init; }
        public IReadOnlyList<DiagnosticReport> Diagnostics { get; init; } = [];
        public int? ValidatorBytes { get; init; }
        public int? RuntimeBytes { get; init; }
        public int? TotalBytes { get; init; }
        public int? GzipBytes { get; init; }
        public int? Loc { get; init; }
        public int? FunctionCount { get; init; }
        public int? MaxIndentationDepth { get; init; }
        public int? HelperCount { get; init; }
        public IReadOnlyList<string> Helpers { get; init; } = [];
        public Dictionary<string, StrictProfileReport>? StrictProfiles { get; set; }
        public MetricDeltas? BaselineDeltas { get; set; }
    }

    private sealed class DiagnosticReport
    {
        public required string Severity { get; init; }
        public string? Code { get; init; }
        public required string Message { get; init; }
        public string? JsonPointer { get; init; }
    }

    private sealed class StrictProfileReport
    {
        public required string Status { get; init; }
        public string? Remediation { get; init; }
        public IReadOnlyList<string> Diagnostics { get; init; } = [];
    }

    private sealed class MetricDeltas
    {
        public string? StatusChange { get; init; }
        public IReadOnlyList<string>? StrictProfileChanges { get; init; }
        public int? ValidatorBytes { get; init; }
        public int? RuntimeBytes { get; init; }
        public int? TotalBytes { get; init; }
        public int? GzipBytes { get; init; }
        public int? Loc { get; init; }
        public int? FunctionCount { get; init; }
        public int? MaxIndentationDepth { get; init; }
        public int? HelperCount { get; init; }
    }

    private sealed class BaselineDocument
    {
        public int FormatVersion { get; init; }
        public IReadOnlyList<BaselineRow> Rows { get; init; } = [];

        public static BaselineDocument FromRows(IReadOnlyList<ReportRow> rows)
        {
            return new BaselineDocument
            {
                FormatVersion = 1,
                Rows = rows
                    .OrderBy(row => row.Target, StringComparer.Ordinal)
                    .ThenBy(row => row.Schema, StringComparer.Ordinal)
                    .Select(row => new BaselineRow
                    {
                        Target = row.Target,
                        Schema = row.Schema,
                        Status = row.Status,
                        ValidatorBytes = row.ValidatorBytes,
                        RuntimeBytes = row.RuntimeBytes,
                        TotalBytes = row.TotalBytes,
                        GzipBytes = row.GzipBytes,
                        Loc = row.Loc,
                        FunctionCount = row.FunctionCount,
                        MaxIndentationDepth = row.MaxIndentationDepth,
                        HelperCount = row.HelperCount,
                        StrictProfiles = row.StrictProfiles is { Count: > 0 }
                            ? row.StrictProfiles
                                .OrderBy(profile => profile.Key, StringComparer.Ordinal)
                                .ToDictionary(profile => profile.Key, profile => profile.Value.Status, StringComparer.Ordinal)
                            : null
                    })
                    .ToArray()
            };
        }
    }

    private sealed class BaselineRow
    {
        public required string Target { get; init; }
        public required string Schema { get; init; }
        public required string Status { get; init; }
        public int? ValidatorBytes { get; init; }
        public int? RuntimeBytes { get; init; }
        public int? TotalBytes { get; init; }
        public int? GzipBytes { get; init; }
        public int? Loc { get; init; }
        public int? FunctionCount { get; init; }
        public int? MaxIndentationDepth { get; init; }
        public int? HelperCount { get; init; }
        public IReadOnlyDictionary<string, string>? StrictProfiles { get; init; }
    }
}
