// Copyright (c) 2026 FormFinch VOF
// Licensed under the PolyForm Noncommercial License 1.0.0.
// See LICENSE file in the project root for full license information.
using System.IO.Compression;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using FormFinch.JsonSchemaValidation.CodeGeneration.Abstractions;
using FormFinch.JsonSchemaValidation.CodeGeneration.JavaScript;
using FormFinch.JsonSchemaValidation.CodeGeneration.TypeScript;
using Xunit;

namespace FormFinch.JsonSchemaValidation.CodeGenerator.Tests;

public sealed partial class OutputQualityReportTests
{
    private const string UpdateBaselineEnvironmentVariable = "JSV_UPDATE_CODEGEN_QUALITY_BASELINE";
    private const string PrintReportEnvironmentVariable = "JSV_PRINT_CODEGEN_QUALITY_REPORT";
    private static readonly UTF8Encoding Utf8NoBom = new(encoderShouldEmitUTF8Identifier: false);

    private readonly Xunit.Abstractions.ITestOutputHelper _testOutput;

    public OutputQualityReportTests(Xunit.Abstractions.ITestOutputHelper testOutput)
    {
        _testOutput = testOutput;
    }

#if NET8_0
    [Fact]
#else
    [Fact(Skip = "The output quality report is generated by net8.0 only to keep gzip baselines stable.")]
#endif
    [Trait("Category", "OutputQuality")]
    public async Task OutputQuality_GeneratesReportedOnlyJsAndTsMetrics()
    {
        var repoRoot = FindRepositoryRoot();
        var reportDirectory = Path.Combine(repoRoot, "artifacts", "codegen-output-quality");
        var baselinePath = Path.Combine(repoRoot, "benchmarks", "codegen-output-quality-baseline.json");
        Directory.CreateDirectory(reportDirectory);

        var scenarios = LoadScenarios(repoRoot);
        var rows = new List<ReportRow>();
        var typeScriptRows = new List<GeneratedTargetRow>();

        foreach (var scenario in scenarios)
        {
            using var schemaDocument = JsonDocument.Parse(scenario.SchemaJson);
            var schema = schemaDocument.RootElement.Clone();

            var javaScriptRow = await GenerateTargetRowAsync(
                new JavaScriptCodeGenerationTarget(),
                new JavaScriptCodeGenerationOptions
                {
                    FormatAssertionEnabled = true,
                    ExternalSchemaDocuments = scenario.ExternalSchemaDocuments,
                    OutputHints = new CodeGenerationOutputHints { BaseFileName = scenario.Id }
                },
                schema,
                scenario.Id);
            rows.Add(javaScriptRow.Row);

            var typeScriptRow = await GenerateTargetRowAsync(
                new TypeScriptCodeGenerationTarget(),
                new TypeScriptCodeGenerationOptions
                {
                    FormatAssertionEnabled = true,
                    ExternalSchemaDocuments = scenario.ExternalSchemaDocuments,
                    OutputHints = new CodeGenerationOutputHints { BaseFileName = scenario.Id }
                },
                schema,
                scenario.Id);
            rows.Add(typeScriptRow.Row);
            if (typeScriptRow.Artifacts.Any(artifact => artifact.Role == GeneratedArtifactRole.Primary))
            {
                typeScriptRows.Add(typeScriptRow);
            }
        }

        ApplyTypeScriptStrictnessProfiles(typeScriptRows);

        var baseline = LoadBaseline(baselinePath);
        foreach (var row in rows)
        {
            row.BaselineDeltas = CalculateBaselineDeltas(row, baseline);
        }

        var qualitySummary = BuildQualitySummary(rows);

        var report = new ReportDocument
        {
            FormatVersion = 1,
            Notes =
            [
                "Reported-only output quality metrics for JavaScript and TypeScript code generation.",
                "All generated artifacts are normalized to UTF-8 text with LF line endings and one trailing newline before measurement.",
                "gzip_bytes is computed by System.IO.Compression.GZipStream with CompressionLevel.Optimal.",
                "function_count is a lightweight regex-based shape signal and can count function-like text in comments or strings.",
                "TypeScript strict_profiles are batched per compiler profile, so failures apply to the generated TS batch rather than isolating one schema.",
                "quality_summary is the headline pass/fail readout for each target. A 'fail' status means the generated code does not compile cleanly under at least one strictness profile (or codegen itself failed). It does not mean runtime validation is broken.",
                "Helper selection correctness is tracked separately by issue #46; this report measures footprint only.",
                "JS/TS deduplication decisions are tracked separately by issue #42.",
                "Lint/static-analysis signals are deferred to follow-up work."
            ],
            QualitySummary = qualitySummary,
            Rows = rows
        };

        var jsonOptions = CreateJsonOptions();
        var markdown = RenderMarkdown(report);
        File.WriteAllText(
            Path.Combine(reportDirectory, "codegen-output-quality.json"),
            JsonSerializer.Serialize(report, jsonOptions),
            Utf8NoBom);
        File.WriteAllText(
            Path.Combine(reportDirectory, "codegen-output-quality.md"),
            markdown,
            Utf8NoBom);

        if (ShouldPrintReport())
        {
            _testOutput.WriteLine("===== Codegen Output Quality Report =====");
            _testOutput.WriteLine(RenderConsole(report));
            _testOutput.WriteLine("===== End Report =====");
        }

        if (ShouldUpdateBaseline())
        {
            Directory.CreateDirectory(Path.GetDirectoryName(baselinePath)!);
            var nextBaseline = BaselineDocument.FromRows(rows);
            File.WriteAllText(
                baselinePath,
                JsonSerializer.Serialize(nextBaseline, jsonOptions),
                Utf8NoBom);
        }
    }

    private static async Task<GeneratedTargetRow> GenerateTargetRowAsync(
        ICodeGenerationTarget target,
        CodeGenerationOptions options,
        JsonElement schema,
        string scenarioId)
    {
        var request = new CodeGenerationRequest
        {
            Schema = schema,
            Options = options
        };

        var capability = await target.GetCapabilitiesAsync(request);
        if (!capability.CanGenerate)
        {
            return new GeneratedTargetRow(new ReportRow
            {
                Target = target.Descriptor.Id,
                Schema = scenarioId,
                Status = "unsupported",
                Diagnostics = MapDiagnostics(capability.Diagnostics),
                Helpers = [],
                StrictProfiles = target.Descriptor.Id == "typescript" ? new Dictionary<string, StrictProfileReport>() : null
            }, []);
        }

        var generation = await target.GenerateAsync(request);
        if (!generation.Success)
        {
            return new GeneratedTargetRow(new ReportRow
            {
                Target = target.Descriptor.Id,
                Schema = scenarioId,
                Status = "generation-failed",
                Diagnostics = MapDiagnostics(generation.Diagnostics),
                Helpers = [],
                StrictProfiles = target.Descriptor.Id == "typescript" ? new Dictionary<string, StrictProfileReport>() : null
            }, []);
        }

        var artifacts = generation.Artifacts
            .OrderByDescending(artifact => artifact.Role == GeneratedArtifactRole.Primary)
            .ThenBy(artifact => artifact.RelativePath, StringComparer.Ordinal)
            .Select(artifact => new NormalizedArtifact(
                artifact.RelativePath,
                artifact.Kind,
                artifact.Role,
                NormalizeSource(artifact.Content)))
            .ToArray();

        var primaryContent = string.Concat(artifacts
            .Where(artifact => artifact.Role == GeneratedArtifactRole.Primary)
            .Select(artifact => artifact.Content));
        var supportContent = string.Concat(artifacts
            .Where(artifact => artifact.Role != GeneratedArtifactRole.Primary)
            .Select(artifact => artifact.Content));
        var allContent = primaryContent + supportContent;
        var helpers = ExtractRuntimeImports(primaryContent).Order(StringComparer.Ordinal).ToArray();

        return new GeneratedTargetRow(new ReportRow
        {
            Target = target.Descriptor.Id,
            Schema = scenarioId,
            Status = "generated",
            Diagnostics = [],
            ValidatorBytes = CountUtf8Bytes(primaryContent),
            RuntimeBytes = CountUtf8Bytes(supportContent),
            TotalBytes = CountUtf8Bytes(primaryContent) + CountUtf8Bytes(supportContent),
            GzipBytes = CountGzipBytes(allContent),
            Loc = CountPhysicalLines(primaryContent),
            FunctionCount = CountFunctions(primaryContent),
            MaxIndentationDepth = CalculateMaxIndentationDepth(primaryContent),
            HelperCount = helpers.Length,
            Helpers = helpers,
            StrictProfiles = target.Descriptor.Id == "typescript" ? new Dictionary<string, StrictProfileReport>() : null
        }, artifacts);
    }

    private static void ApplyTypeScriptStrictnessProfiles(IReadOnlyList<GeneratedTargetRow> typeScriptRows)
    {
        foreach (var row in typeScriptRows)
        {
            row.Row.StrictProfiles ??= new Dictionary<string, StrictProfileReport>();
        }

        if (typeScriptRows.Count == 0)
        {
            return;
        }

        if (!TypeScriptCompiler.IsAvailable())
        {
            foreach (var row in typeScriptRows)
            {
                foreach (var profile in GetStrictnessProfiles())
                {
                    row.Row.StrictProfiles![profile.Name] = new StrictProfileReport
                    {
                        Status = "unavailable",
                        Remediation = "unknown",
                        Diagnostics = ["TypeScript compiler 'tsc' is not available."]
                    };
                }
            }
            return;
        }

        var tempRoot = Path.Combine(Path.GetTempPath(), "jsv-output-quality-ts-" + Guid.NewGuid().ToString("N"));
        var sourceRoot = Path.Combine(tempRoot, "src");
        Directory.CreateDirectory(sourceRoot);
        try
        {
            var runtimePath = Path.Combine(sourceRoot, TsRuntime.FileName);
            File.WriteAllText(runtimePath, NormalizeSource(TsRuntime.GetSource()), Utf8NoBom);

            var sourcePaths = new List<string> { runtimePath };
            foreach (var generatedRow in typeScriptRows)
            {
                var primaryArtifact = generatedRow.Artifacts.SingleOrDefault(artifact => artifact.Role == GeneratedArtifactRole.Primary);
                if (primaryArtifact == null)
                {
                    foreach (var profile in GetStrictnessProfiles())
                    {
                        generatedRow.Row.StrictProfiles![profile.Name] = new StrictProfileReport
                        {
                            Status = "skipped",
                            Remediation = "unknown",
                            Diagnostics = ["No primary TypeScript artifact was emitted for this scenario."]
                        };
                    }

                    continue;
                }

                var sourcePath = Path.Combine(sourceRoot, $"{generatedRow.Row.Schema}.ts");
                File.WriteAllText(sourcePath, primaryArtifact.Content, Utf8NoBom);
                sourcePaths.Add(sourcePath);
            }

            foreach (var profile in GetStrictnessProfiles())
            {
                var outputDirectory = Path.Combine(tempRoot, "out", profile.Name);
                var compileResult = TypeScriptCompiler.Compile(
                    sourcePaths,
                    outputDirectory,
                    ecmaScriptTarget: "ES2020",
                    options: profile.Options,
                    timeoutMilliseconds: 240_000);
                var report = new StrictProfileReport
                {
                    Status = compileResult.Success ? "passed" : "failed",
                    Remediation = compileResult.Success ? null : CategorizeTypeScriptFailure(compileResult),
                    Diagnostics = BuildCompilerDiagnostics(compileResult, tempRoot)
                };

                foreach (var generatedRow in typeScriptRows)
                {
                    generatedRow.Row.StrictProfiles![profile.Name] = report;
                }
            }
        }
        finally
        {
            try { Directory.Delete(tempRoot, recursive: true); } catch { /* best effort */ }
        }
    }

    private static IReadOnlyList<Scenario> LoadScenarios(string repoRoot)
    {
        return
        [
            new("primitive-string", """{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"string"}"""),
            new("integer-constraints", """{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"integer","minimum":3,"multipleOf":2}"""),
            new("object-required-additional-properties", """
                {
                  "$schema": "https://json-schema.org/draft/2020-12/schema",
                  "type": "object",
                  "required": ["name"],
                  "properties": {
                    "name": { "type": "string" },
                    "age": { "type": "integer", "minimum": 0 }
                  },
                  "additionalProperties": false
                }
                """),
            new("enum-const", """{"$schema":"https://json-schema.org/draft/2020-12/schema","enum":["red","green",3],"const":"red"}"""),
            new("format-assertion", """{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"string","format":"email"}"""),
            new("external-ref", """{"$schema":"https://json-schema.org/draft/2020-12/schema","$ref":"https://example.com/schemas/external-string"}""",
                new Dictionary<string, string>(StringComparer.Ordinal)
                {
                    ["https://example.com/schemas/external-string"] =
                        """{"$id":"https://example.com/schemas/external-string","type":"string","minLength":2}"""
                }),
            new("dynamic-ref", """
                {
                  "$schema": "https://json-schema.org/draft/2020-12/schema",
                  "$dynamicAnchor": "node",
                  "type": "object",
                  "properties": {
                    "value": { "type": "string" },
                    "child": { "$dynamicRef": "#node" }
                  }
                }
                """),
            new("unevaluated", """
                {
                  "$schema": "https://json-schema.org/draft/2020-12/schema",
                  "type": "object",
                  "properties": {
                    "items": {
                      "type": "array",
                      "prefixItems": [{ "type": "string" }],
                      "unevaluatedItems": false
                    }
                  },
                  "unevaluatedProperties": false
                }
                """),
            new("production-package-json", File.ReadAllText(Path.Combine(repoRoot, "JsonSchemaValidationTests", "ProductionSchemas", "PackageJson", "schema.json"))),
            new("production-tsconfig", File.ReadAllText(Path.Combine(repoRoot, "JsonSchemaValidationTests", "ProductionSchemas", "TsConfig", "schema.json"))),
            new("production-github-workflow", File.ReadAllText(Path.Combine(repoRoot, "JsonSchemaValidationTests", "ProductionSchemas", "GithubWorkflow", "schema.json")))
        ];
    }

    private static IReadOnlyDictionary<string, BaselineRow> LoadBaseline(string baselinePath)
    {
        if (!File.Exists(baselinePath))
        {
            return new Dictionary<string, BaselineRow>(StringComparer.Ordinal);
        }

        var baseline = JsonSerializer.Deserialize<BaselineDocument>(
            File.ReadAllText(baselinePath, Utf8NoBom),
            CreateJsonOptions());
        return baseline?.Rows.ToDictionary(row => GetBaselineKey(row.Target, row.Schema), StringComparer.Ordinal)
            ?? new Dictionary<string, BaselineRow>(StringComparer.Ordinal);
    }

    private static MetricDeltas? CalculateBaselineDeltas(ReportRow row, IReadOnlyDictionary<string, BaselineRow> baseline)
    {
        if (!baseline.TryGetValue(GetBaselineKey(row.Target, row.Schema), out var baselineRow))
        {
            return null;
        }

        return new MetricDeltas
        {
            ValidatorBytes = Subtract(row.ValidatorBytes, baselineRow.ValidatorBytes),
            RuntimeBytes = Subtract(row.RuntimeBytes, baselineRow.RuntimeBytes),
            TotalBytes = Subtract(row.TotalBytes, baselineRow.TotalBytes),
            GzipBytes = Subtract(row.GzipBytes, baselineRow.GzipBytes),
            Loc = Subtract(row.Loc, baselineRow.Loc),
            FunctionCount = Subtract(row.FunctionCount, baselineRow.FunctionCount),
            MaxIndentationDepth = Subtract(row.MaxIndentationDepth, baselineRow.MaxIndentationDepth),
            HelperCount = Subtract(row.HelperCount, baselineRow.HelperCount)
        };
    }

    private static string NormalizeSource(string source)
    {
        var normalized = source.Replace("\r\n", "\n", StringComparison.Ordinal).Replace('\r', '\n');
        return normalized.TrimEnd('\n') + "\n";
    }

    private static int CountUtf8Bytes(string source) => Utf8NoBom.GetByteCount(source);

    private static int CountPhysicalLines(string source) => source.Length == 0 ? 0 : source.Split('\n').Length - 1;

    private static int CountFunctions(string source)
    {
        return FunctionRegex().Matches(source).Count + ArrowFunctionRegex().Matches(source).Count;
    }

    private static int CalculateMaxIndentationDepth(string source)
    {
        var maxColumns = 0;
        foreach (var line in source.Split('\n'))
        {
            var columns = 0;
            foreach (var c in line)
            {
                if (c == ' ')
                {
                    columns++;
                }
                else if (c == '\t')
                {
                    columns += 4;
                }
                else
                {
                    break;
                }
            }

            maxColumns = Math.Max(maxColumns, columns);
        }

        return maxColumns / 2;
    }

    private static int CountGzipBytes(string source)
    {
        var bytes = Utf8NoBom.GetBytes(source);
        using var memoryStream = new MemoryStream();
        using (var gzipStream = new GZipStream(memoryStream, CompressionLevel.Optimal, leaveOpen: true))
        {
            gzipStream.Write(bytes, 0, bytes.Length);
        }

        return checked((int)memoryStream.Length);
    }

    private static IReadOnlyList<string> ExtractRuntimeImports(string source)
    {
        var helpers = new SortedSet<string>(StringComparer.Ordinal);
        foreach (Match match in RuntimeImportRegex().Matches(source))
        {
            var names = match.Groups["names"].Value.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            foreach (var name in names)
            {
                var cleaned = name;
                var asIndex = cleaned.IndexOf(" as ", StringComparison.Ordinal);
                if (asIndex >= 0)
                {
                    cleaned = cleaned[..asIndex].Trim();
                }

                if (cleaned.Length > 0)
                {
                    helpers.Add(cleaned);
                }
            }
        }

        return helpers.ToArray();
    }

    private static string RenderConsole(ReportDocument report)
    {
        var sb = new StringBuilder();
        sb.AppendLine("Codegen Output Quality");
        sb.AppendLine("======================");
        sb.AppendLine();
        sb.AppendLine("Quality Summary");
        sb.AppendLine("---------------");
        sb.AppendLine("FAIL = generated code does not compile cleanly under at least one strictness profile");
        sb.AppendLine("       (or codegen itself failed). It does NOT mean runtime validation is broken.");
        sb.AppendLine();

        var summaryHeaders = new[] { "target", "status", "pass", "fail", "failing strict profiles" };
        var summaryRows = report.QualitySummary
            .OrderBy(entry => entry.Target, StringComparer.Ordinal)
            .Select(entry => new[]
            {
                entry.Target,
                entry.Status.ToUpperInvariant(),
                entry.PassingScenarioCount.ToString(System.Globalization.CultureInfo.InvariantCulture),
                entry.FailingScenarioCount.ToString(System.Globalization.CultureInfo.InvariantCulture),
                entry.FailingProfiles.Count == 0 ? "-" : string.Join(", ", entry.FailingProfiles)
            })
            .ToArray();
        AppendPlainTable(sb, summaryHeaders, summaryRows, rightAlignColumns: [2, 3]);
        sb.AppendLine();

        sb.AppendLine("Per-Schema Metrics");
        sb.AppendLine("------------------");
        var metricHeaders = new[] { "target", "schema", "status", "validator", "runtime", "total", "gzip", "loc", "fns", "depth", "helpers", "deltas" };
        var metricRows = report.Rows
            .OrderBy(row => row.Target, StringComparer.Ordinal)
            .ThenBy(row => row.Schema, StringComparer.Ordinal)
            .Select(row => new[]
            {
                row.Target,
                row.Schema,
                row.Status,
                FormatNullable(row.ValidatorBytes),
                FormatNullable(row.RuntimeBytes),
                FormatNullable(row.TotalBytes),
                FormatNullable(row.GzipBytes),
                FormatNullable(row.Loc),
                FormatNullable(row.FunctionCount),
                FormatNullable(row.MaxIndentationDepth),
                FormatNullable(row.HelperCount),
                FormatDeltas(row.BaselineDeltas)
            })
            .ToArray();
        AppendPlainTable(sb, metricHeaders, metricRows, rightAlignColumns: [3, 4, 5, 6, 7, 8, 9, 10]);
        sb.AppendLine();

        var tsRows = report.Rows
            .Where(row => row.StrictProfiles is { Count: > 0 })
            .OrderBy(row => row.Schema, StringComparer.Ordinal)
            .ToArray();
        if (tsRows.Length > 0)
        {
            sb.AppendLine("TypeScript Strictness Detail");
            sb.AppendLine("----------------------------");
            var profileNames = tsRows
                .SelectMany(row => row.StrictProfiles!.Keys)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(name => name, StringComparer.Ordinal)
                .ToArray();
            var strictHeaders = new[] { "schema" }.Concat(profileNames).ToArray();
            var strictRows = tsRows.Select(row =>
            {
                var cells = new string[strictHeaders.Length];
                cells[0] = row.Schema;
                for (var i = 0; i < profileNames.Length; i++)
                {
                    cells[i + 1] = row.StrictProfiles!.TryGetValue(profileNames[i], out var profile)
                        ? profile.Status
                        : "-";
                }
                return cells;
            }).ToArray();
            AppendPlainTable(sb, strictHeaders, strictRows, rightAlignColumns: []);
            sb.AppendLine();
        }

        sb.AppendLine("Notes");
        sb.AppendLine("-----");
        foreach (var note in report.Notes)
        {
            sb.AppendLine("- " + note);
        }

        return sb.ToString();
    }

    private static void AppendPlainTable(
        StringBuilder sb,
        IReadOnlyList<string> headers,
        IReadOnlyList<string[]> rows,
        IReadOnlyList<int> rightAlignColumns)
    {
        var widths = new int[headers.Count];
        for (var i = 0; i < headers.Count; i++)
        {
            widths[i] = headers[i].Length;
        }
        foreach (var row in rows)
        {
            for (var i = 0; i < headers.Count; i++)
            {
                if (row[i].Length > widths[i])
                {
                    widths[i] = row[i].Length;
                }
            }
        }

        AppendPlainTableRow(sb, headers.ToArray(), widths, rightAlignColumns);
        var separator = new string[headers.Count];
        for (var i = 0; i < headers.Count; i++)
        {
            separator[i] = new string('-', widths[i]);
        }
        AppendPlainTableRow(sb, separator, widths, []);
        foreach (var row in rows)
        {
            AppendPlainTableRow(sb, row, widths, rightAlignColumns);
        }
    }

    private static void AppendPlainTableRow(
        StringBuilder sb,
        string[] cells,
        int[] widths,
        IReadOnlyList<int> rightAlignColumns)
    {
        for (var i = 0; i < cells.Length; i++)
        {
            if (i > 0)
            {
                sb.Append("  ");
            }
            sb.Append(rightAlignColumns.Contains(i) ? cells[i].PadLeft(widths[i]) : cells[i].PadRight(widths[i]));
        }
        sb.AppendLine();
    }

    private static string RenderMarkdown(ReportDocument report)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Codegen Output Quality");
        sb.AppendLine();

        sb.AppendLine("## Quality Summary");
        sb.AppendLine();
        sb.AppendLine("Headline pass/fail per target. **fail** means the generated code does not compile cleanly under at least one strictness profile (or codegen itself failed). It does not mean runtime validation is broken.");
        sb.AppendLine();
        sb.AppendLine("| target | status | passing scenarios | failing scenarios | failing strict profiles |");
        sb.AppendLine("| --- | --- | ---: | ---: | --- |");
        foreach (var entry in report.QualitySummary.OrderBy(entry => entry.Target, StringComparer.Ordinal))
        {
            var failingProfiles = entry.FailingProfiles.Count == 0
                ? "—"
                : string.Join(", ", entry.FailingProfiles);
            sb.Append("| ");
            sb.Append(EscapeMarkdown(entry.Target));
            sb.Append(" | ");
            sb.Append(entry.Status.ToUpperInvariant());
            sb.Append(" | ");
            sb.Append(entry.PassingScenarioCount);
            sb.Append(" | ");
            sb.Append(entry.FailingScenarioCount);
            sb.Append(" | ");
            sb.Append(EscapeMarkdown(failingProfiles));
            sb.AppendLine(" |");
        }

        sb.AppendLine();
        sb.AppendLine("## Notes");
        sb.AppendLine();
        foreach (var note in report.Notes)
        {
            sb.AppendLine($"- {note}");
        }

        sb.AppendLine();
        sb.AppendLine("## Per-Schema Metrics");
        sb.AppendLine();
        sb.AppendLine("| target | schema | status | validator bytes | runtime bytes | total bytes | gzip bytes | LOC | functions | max depth | helpers | deltas |");
        sb.AppendLine("| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |");
        foreach (var row in report.Rows.OrderBy(row => row.Target, StringComparer.Ordinal).ThenBy(row => row.Schema, StringComparer.Ordinal))
        {
            sb.Append("| ");
            sb.Append(EscapeMarkdown(row.Target));
            sb.Append(" | ");
            sb.Append(EscapeMarkdown(row.Schema));
            sb.Append(" | ");
            sb.Append(EscapeMarkdown(row.Status));
            sb.Append(" | ");
            sb.Append(FormatNullable(row.ValidatorBytes));
            sb.Append(" | ");
            sb.Append(FormatNullable(row.RuntimeBytes));
            sb.Append(" | ");
            sb.Append(FormatNullable(row.TotalBytes));
            sb.Append(" | ");
            sb.Append(FormatNullable(row.GzipBytes));
            sb.Append(" | ");
            sb.Append(FormatNullable(row.Loc));
            sb.Append(" | ");
            sb.Append(FormatNullable(row.FunctionCount));
            sb.Append(" | ");
            sb.Append(FormatNullable(row.MaxIndentationDepth));
            sb.Append(" | ");
            sb.Append(FormatNullable(row.HelperCount));
            sb.Append(" | ");
            sb.Append(EscapeMarkdown(FormatDeltas(row.BaselineDeltas)));
            sb.AppendLine(" |");
        }

        sb.AppendLine();
        sb.AppendLine("## TypeScript Strictness Detail");
        sb.AppendLine();
        sb.AppendLine("Each row shows whether the generated TypeScript for a scenario compiles under each strictness profile. `failed` indicates `tsc` reported errors under that profile.");
        sb.AppendLine();
        foreach (var row in report.Rows.Where(row => row.StrictProfiles is { Count: > 0 }).OrderBy(row => row.Schema, StringComparer.Ordinal))
        {
            sb.AppendLine($"- `{row.Schema}`: {string.Join(", ", row.StrictProfiles!.Select(profile => $"{profile.Key}={profile.Value.Status}"))}");
        }

        return sb.ToString();
    }

    private static IReadOnlyList<QualitySummaryEntry> BuildQualitySummary(IReadOnlyList<ReportRow> rows)
    {
        var entries = new List<QualitySummaryEntry>();
        foreach (var group in rows.GroupBy(row => row.Target, StringComparer.Ordinal).OrderBy(group => group.Key, StringComparer.Ordinal))
        {
            var passingScenarios = 0;
            var failingScenarios = 0;
            var failingProfiles = new SortedSet<string>(StringComparer.Ordinal);

            foreach (var row in group)
            {
                var rowFailed = false;

                if (row.Status != "generated")
                {
                    rowFailed = true;
                    failingProfiles.Add($"codegen:{row.Status}");
                }

                if (row.StrictProfiles is { Count: > 0 })
                {
                    foreach (var profile in row.StrictProfiles)
                    {
                        if (profile.Value.Status == "failed")
                        {
                            rowFailed = true;
                            failingProfiles.Add(profile.Key);
                        }
                    }
                }

                if (rowFailed)
                {
                    failingScenarios++;
                }
                else
                {
                    passingScenarios++;
                }
            }

            entries.Add(new QualitySummaryEntry
            {
                Target = group.Key,
                Status = failingScenarios == 0 ? "pass" : "fail",
                PassingScenarioCount = passingScenarios,
                FailingScenarioCount = failingScenarios,
                FailingProfiles = failingProfiles.ToArray()
            });
        }

        return entries;
    }

    private static IReadOnlyList<StrictnessProfile> GetStrictnessProfiles()
    {
        return
        [
            new("strict-no-implicit-any", new TypeScriptCompilerOptions { Strict = true, NoImplicitAny = true }),
            new("no-unchecked-indexed-access", new TypeScriptCompilerOptions { Strict = true, NoImplicitAny = true, NoUncheckedIndexedAccess = true }),
            new("exact-optional-property-types", new TypeScriptCompilerOptions { Strict = true, NoImplicitAny = true, ExactOptionalPropertyTypes = true }),
            new("combined-extra-strict", new TypeScriptCompilerOptions
            {
                Strict = true,
                NoImplicitAny = true,
                NoUncheckedIndexedAccess = true,
                ExactOptionalPropertyTypes = true
            })
        ];
    }

    private static IReadOnlyList<DiagnosticReport> MapDiagnostics(IReadOnlyList<CodeGenerationDiagnostic> diagnostics)
    {
        return diagnostics.Select(diagnostic => new DiagnosticReport
        {
            Severity = diagnostic.Severity.ToString(),
            Code = diagnostic.Code,
            Message = diagnostic.Message,
            JsonPointer = diagnostic.JsonPointer
        }).ToArray();
    }

    private static IReadOnlyList<string> BuildCompilerDiagnostics(TypeScriptCompilationResult result, string? tempRoot = null)
    {
        if (result.Success)
        {
            return [];
        }

        var lines = new[] { result.Error, result.StandardError, result.StandardOutput }
            .Where(value => !string.IsNullOrWhiteSpace(value))
            .SelectMany(value => NormalizeDiagnosticText(value!, tempRoot).Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            .ToArray();
        const int maxLines = 80;
        if (lines.Length <= maxLines)
        {
            return lines;
        }

        return lines.Take(maxLines)
            .Append($"... truncated {lines.Length - maxLines} additional diagnostic lines")
            .ToArray();
    }

    private static string CategorizeTypeScriptFailure(TypeScriptCompilationResult result)
    {
        var text = string.Join('\n', BuildCompilerDiagnostics(result));
        if (text.Contains("jsv-runtime", StringComparison.OrdinalIgnoreCase))
        {
            return "runtime-types";
        }

        if (text.Contains("validator", StringComparison.OrdinalIgnoreCase))
        {
            return "generated-code";
        }

        return "unknown";
    }

    private static string NormalizeDiagnosticText(string text, string? tempRoot)
    {
        var normalized = text.Replace("\r\n", "\n", StringComparison.Ordinal).Replace('\r', '\n');
        if (!string.IsNullOrWhiteSpace(tempRoot))
        {
            normalized = normalized
                .Replace(tempRoot, "<temp>", StringComparison.OrdinalIgnoreCase)
                .Replace(tempRoot.Replace('\\', '/'), "<temp>", StringComparison.OrdinalIgnoreCase);
        }

        return normalized.Trim();
    }

    private static JsonSerializerOptions CreateJsonOptions()
    {
        return new JsonSerializerOptions
        {
            WriteIndented = true,
            PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower
        };
    }

    private static bool ShouldUpdateBaseline()
    {
        var value = Environment.GetEnvironmentVariable(UpdateBaselineEnvironmentVariable);
        return string.Equals(value, "1", StringComparison.Ordinal) ||
               string.Equals(value, "true", StringComparison.OrdinalIgnoreCase);
    }

    private static bool ShouldPrintReport()
    {
        var value = Environment.GetEnvironmentVariable(PrintReportEnvironmentVariable);
        return string.Equals(value, "1", StringComparison.Ordinal) ||
               string.Equals(value, "true", StringComparison.OrdinalIgnoreCase);
    }

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory != null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "JsonSchemaValidationSolution.slnx")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new InvalidOperationException("Could not locate repository root.");
    }

    private static string GetBaselineKey(string target, string schema) => target + ":" + schema;

    private static int? Subtract(int? actual, int? baseline)
    {
        return actual.HasValue && baseline.HasValue ? actual.Value - baseline.Value : null;
    }

    private static string FormatNullable(int? value) => value?.ToString(System.Globalization.CultureInfo.InvariantCulture) ?? "";

    private static string FormatDeltas(MetricDeltas? deltas)
    {
        if (deltas == null)
        {
            return "";
        }

        if (!deltas.TotalBytes.HasValue &&
            !deltas.GzipBytes.HasValue &&
            !deltas.Loc.HasValue)
        {
            return "";
        }

        return $"total {FormatDelta(deltas.TotalBytes)}, gzip {FormatDelta(deltas.GzipBytes)}, loc {FormatDelta(deltas.Loc)}";
    }

    private static string FormatDelta(int? value)
    {
        if (!value.HasValue)
        {
            return "";
        }

        return value.Value >= 0 ? "+" + value.Value.ToString(System.Globalization.CultureInfo.InvariantCulture) : value.Value.ToString(System.Globalization.CultureInfo.InvariantCulture);
    }

    private static string EscapeMarkdown(string value) => value.Replace("|", "\\|", StringComparison.Ordinal);

    [GeneratedRegex(@"\bfunction\b", RegexOptions.CultureInvariant)]
    private static partial Regex FunctionRegex();

    [GeneratedRegex(@"=>", RegexOptions.CultureInvariant)]
    private static partial Regex ArrowFunctionRegex();

    [GeneratedRegex(@"import\s+(?:type\s+)?\{\s*(?<names>[^}]+)\s*\}\s+from\s+[""'][^""']*jsv-runtime\.js[""']", RegexOptions.CultureInvariant)]
    private static partial Regex RuntimeImportRegex();

    private sealed record Scenario(
        string Id,
        string SchemaJson,
        IReadOnlyDictionary<string, string>? ExternalSchemaDocuments = null);

    private sealed record GeneratedTargetRow(ReportRow Row, IReadOnlyList<NormalizedArtifact> Artifacts);

    private sealed record NormalizedArtifact(
        string RelativePath,
        GeneratedArtifactKind Kind,
        GeneratedArtifactRole Role,
        string Content);

    private sealed record StrictnessProfile(string Name, TypeScriptCompilerOptions Options);

    private sealed class ReportDocument
    {
        public int FormatVersion { get; init; }
        public IReadOnlyList<string> Notes { get; init; } = [];
        public IReadOnlyList<QualitySummaryEntry> QualitySummary { get; init; } = [];
        public IReadOnlyList<ReportRow> Rows { get; init; } = [];
    }

    private sealed class QualitySummaryEntry
    {
        public required string Target { get; init; }
        public required string Status { get; init; }
        public int PassingScenarioCount { get; init; }
        public int FailingScenarioCount { get; init; }
        public IReadOnlyList<string> FailingProfiles { get; init; } = [];
    }

    private sealed class ReportRow
    {
        public required string Target { get; init; }
        public required string Schema { get; init; }
        public required string Status { get; init; }
        public IReadOnlyList<DiagnosticReport> Diagnostics { get; init; } = [];
        public int? ValidatorBytes { get; init; }
        public int? RuntimeBytes { get; init; }
        public int? TotalBytes { get; init; }
        public int? GzipBytes { get; init; }
        public int? Loc { get; init; }
        public int? FunctionCount { get; init; }
        public int? MaxIndentationDepth { get; init; }
        public int? HelperCount { get; init; }
        public IReadOnlyList<string> Helpers { get; init; } = [];
        public Dictionary<string, StrictProfileReport>? StrictProfiles { get; set; }
        public MetricDeltas? BaselineDeltas { get; set; }
    }

    private sealed class DiagnosticReport
    {
        public required string Severity { get; init; }
        public string? Code { get; init; }
        public required string Message { get; init; }
        public string? JsonPointer { get; init; }
    }

    private sealed class StrictProfileReport
    {
        public required string Status { get; init; }
        public string? Remediation { get; init; }
        public IReadOnlyList<string> Diagnostics { get; init; } = [];
    }

    private sealed class MetricDeltas
    {
        public int? ValidatorBytes { get; init; }
        public int? RuntimeBytes { get; init; }
        public int? TotalBytes { get; init; }
        public int? GzipBytes { get; init; }
        public int? Loc { get; init; }
        public int? FunctionCount { get; init; }
        public int? MaxIndentationDepth { get; init; }
        public int? HelperCount { get; init; }
    }

    private sealed class BaselineDocument
    {
        public int FormatVersion { get; init; }
        public IReadOnlyList<BaselineRow> Rows { get; init; } = [];

        public static BaselineDocument FromRows(IReadOnlyList<ReportRow> rows)
        {
            return new BaselineDocument
            {
                FormatVersion = 1,
                Rows = rows
                    .OrderBy(row => row.Target, StringComparer.Ordinal)
                    .ThenBy(row => row.Schema, StringComparer.Ordinal)
                    .Select(row => new BaselineRow
                    {
                        Target = row.Target,
                        Schema = row.Schema,
                        Status = row.Status,
                        ValidatorBytes = row.ValidatorBytes,
                        RuntimeBytes = row.RuntimeBytes,
                        TotalBytes = row.TotalBytes,
                        GzipBytes = row.GzipBytes,
                        Loc = row.Loc,
                        FunctionCount = row.FunctionCount,
                        MaxIndentationDepth = row.MaxIndentationDepth,
                        HelperCount = row.HelperCount
                    })
                    .ToArray()
            };
        }
    }

    private sealed class BaselineRow
    {
        public required string Target { get; init; }
        public required string Schema { get; init; }
        public required string Status { get; init; }
        public int? ValidatorBytes { get; init; }
        public int? RuntimeBytes { get; init; }
        public int? TotalBytes { get; init; }
        public int? GzipBytes { get; init; }
        public int? Loc { get; init; }
        public int? FunctionCount { get; init; }
        public int? MaxIndentationDepth { get; init; }
        public int? HelperCount { get; init; }
    }
}
